#!/usr/bin/env python

import json
import svm.nix


repo_url = 'https://github.com/Winetricks/winetricks.git'

with open('source.json', 'w') as f:
    prefetch_result = svm.nix.prefetch_git(repo_url)
    json.dump(
        {
            'url': prefetch_result['url'],
            'rev': prefetch_result['rev'],
            'sha256': prefetch_result['sha256']
        },
        f
    )
